name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Hello! Thank you so much for creating your first issue in '@gstj/safe-jsx'! We appreciate your contribution and will review it as soon as possible. In the meantime, please make sure you have followed our guidelines and codes of conduct."
        pr-message: "🎉 Congratulations on making your first pull request in '@gstj/safe-jsx'! We appreciate your contribution and will review it as soon as possible. Thank you for helping us make this project better."
